default: &default
  # adapter: sqlite3
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  
test:
  # <<: *default
  adapter: postgresql
  host: postgres
  encoding: unicode
  database: alishop_test
  username: postgres
  password: