default: &default
  # adapter: sqlite3
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
test:
  adapter: postgresql
  # host: postgres
  encoding: unicode
  database: alishop_test
  username: postgres
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: alishop_development
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode  
  database: alishop_production
  username: postgres
  password:
